# キーバインド

# 設定リロード
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# copy-mode を vim ライクに
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
