# 一般オプション

set -g mouse on
setw -g mode-keys vi

# Neovim 連携（autoread, FocusGained が正しく動作するために必要）
set -sg escape-time 10
set -g focus-events on

# True color サポート
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
