# TPM (tmux plugin manager)

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# TPM 自動インストール（未インストール時）
if-shell "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# TPM 初期化（この行は必ず最後に置く）
run '~/.config/tmux/plugins/tpm/tpm'
